In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\credit_risk_dataset.csv")

In [6]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,Bachelors,Own,0
1,49,116646.0,43663,315,5,PhD,Own,0
2,35,61157.0,18994,428,8,Masters,Own,1
3,63,52154.0,28499,408,26,Bachelors,Rent,0
4,28,148876.0,28040,832,3,Masters,Own,1


In [7]:
df.select_dtypes(include= ['object'])

,Education_Level,Housing_Status
0,Bachelors,Own
1,PhD,Own
2,Masters,Own
3,Bachelors,Rent
4,Masters,Own
...,...,...
995,PhD,Rent
996,High School,Own
997,Masters,Rent
998,PhD,Own


In [8]:
df['Education_Level'].unique()

array(['Bachelors', 'PhD', 'Masters', 'High School'], dtype=object)

In [9]:
order={'Bachelors':1, 'PhD':3, 'Masters':2, 'High School':0}

In [10]:
df['Education_Level']=df['Education_Level'].map(order)

In [11]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,1,Own,0
1,49,116646.0,43663,315,5,3,Own,0
2,35,61157.0,18994,428,8,2,Own,1
3,63,52154.0,28499,408,26,1,Rent,0
4,28,148876.0,28040,832,3,2,Own,1


In [12]:
df['Housing_Status'].unique()

array(['Own', 'Rent', 'Mortgage'], dtype=object)

In [13]:
df['Housing_Status'] = df['Housing_Status'].map({'Own':2, 'Rent':0, 'Mortgage':1})

In [14]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,1,2,0
1,49,116646.0,43663,315,5,3,2,0
2,35,61157.0,18994,428,8,2,2,1
3,63,52154.0,28499,408,26,1,0,0
4,28,148876.0,28040,832,3,2,2,1


In [15]:
df.select_dtypes(include= ['object'])

""
0
1
2
3
4
...
995
996
997
998


In [16]:
df['Income'] = df['Income'].replace(np.nan, df['Income'].mean())

In [17]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,1,2,0
1,49,116646.0,43663,315,5,3,2,0
2,35,61157.0,18994,428,8,2,2,1
3,63,52154.0,28499,408,26,1,0,0
4,28,148876.0,28040,832,3,2,2,1


In [18]:
from sklearn.preprocessing import RobustScaler

In [19]:
rs = RobustScaler()

In [27]:
X1 = pd.DataFrame(arr1, columns=['Age', 'Income', 'Loan_Amount', 'Credit_Score', 'Employment_Years',
       'Education_Level', 'Housing_Status'])

In [26]:
arr1 = rs.fit_transform(X)

In [25]:
X.keys()

Index(['Age', 'Income', 'Loan_Amount', 'Credit_Score', 'Employment_Years',
       'Education_Level', 'Housing_Status'],
      dtype='object')

In [23]:
X = df.drop(columns=['Default'])

In [24]:
y = df['Default']

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, x_test, y_train, y_test = train_test_split(X1,y,test_size=.2,random_state=13)

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
lr= LogisticRegression(max_iter=1000, class_weight='balanced')

In [32]:
lr.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [47]:
y_pred = lr.predict(x_test)

In [48]:
lr.score(x_test, y_test)

0.515

In [49]:
from sklearn.metrics import confusion_matrix

In [50]:
confusion_matrix(y_test, y_pred)

array([[84, 83],
       [14, 19]], dtype=int64)

In [51]:
from sklearn.metrics import precision_score, recall_score

In [52]:
print(precision_score(y_test, y_pred), recall_score(y_test, y_pred))

0.18627450980392157 0.5757575757575758


In [39]:
import pickle

pickle.dump(lr, open("credit_model.pkl", "wb"))

print("Model Saved Successfully")

Model Saved Successfully


In [53]:
import pickle

pickle.dump(lr, open("credit_model.pkl", "wb"))
pickle.dump(rs, open("scaler.pkl", "wb"))

print("Model and Scaler Saved Successfully")

Model and Scaler Saved Successfully


In [41]:
print(y.value_counts())

Default
0    862
1    138
Name: count, dtype: int64


In [42]:
print(df['Education_Level'].unique())
print(df['Housing_Status'].unique())

[1 3 2 0]
[2 0 1]


In [55]:
print("Train Accuracy:", lr.score(X_train, y_train))
print("Test Accuracy:", lr.score(x_test, y_test))

Train Accuracy: 0.555
Test Accuracy: 0.515


In [45]:
sample = [[35,80000,10000,750,8,2,2]]

sample = rs.transform(sample)

print(lr.predict(sample))

[1]


d:\Python\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(
d:\Python\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [46]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200, random_state=42)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [56]:
df.corr(numeric_only=True)['Default'].sort_values()

Age                -0.091566
Loan_Amount        -0.046267
Employment_Years   -0.016417
Income             -0.010130
Housing_Status     -0.004463
Credit_Score        0.009403
Education_Level     0.034555
Default             1.000000
Name: Default, dtype: float64